---
- hosts: lbs 
  tasks:
  - name: apt-get udpate
    apt:
            update_cache: yes
  - name: apt-get upgrade
    apt:
            upgrade: yes

  - name: install haproxy
    apt:
            name: haproxy
            state: present

  - name: Telegraf apt-get update_cache
    apt:
            update_cache: yes

  - name: Telegraf apt-get install telegraf
    apt:
            name: telegraf
            state: present
  - name: Update telegraf config
    copy:
            src: /home/tokugero/repos/digitalocean/roles/lbs/telegraf.conf
            dest: /etc/telegraf/telegraf.conf
            owner: root
            group: root
            mode: 0644

  - name: Restart telegraf
    systemd:
            name: telegraf
            state: restarted

